import test from 'node:test';import assert from 'node:assert/strict';import {createIntentStore} from '../intent-store.mjs';import {fixtureAttempt} from './intent-fixtures.mjs';import {createDesk} from '../server.mjs';
test('review binds exact raw attempt/fields; repeated review is idempotent and replacement cannot inherit acceptance',()=>{
 const f=fixtureAttempt();let current=JSON.stringify(f.attempt),store=createIntentStore(f.bindings,{readAttempt:()=>current}),p=store.proposal('D1');assert.equal(p.state,'requires_human_semantic_review');const body={case_id:'D1',proposal_fingerprint:p.proposal_fingerprint,semantic_confirmation:true},r=store.review(body);assert.deepEqual(store.review(body),r);assert.ok(store.validateBinding(r.binding,r.query));assert.throws(()=>store.validateBinding(r.binding,{...r.query,source_weekstatus:'Weekend'}),{code:'STALE_INTENT_QUERY'});
 const changed=fixtureAttempt('D1',{...f.query,operation:'count_source_rows'});current=JSON.stringify(changed.attempt);assert.throws(()=>store.review(body),{code:'STALE_INTENT'});assert.throws(()=>store.validateBinding(r.binding,r.query),{code:'STALE_INTENT'});assert.notEqual(store.proposal('D1').proposal_fingerprint,p.proposal_fingerprint);
});
test('missing, forged and policy-rejected attempts remain inspectable without review authority',()=>{
 const f=fixtureAttempt();assert.equal(createIntentStore(f.bindings,{readAttempt:()=>null}).proposal('D1').state,'not_run');const forged=createIntentStore(f.bindings,{readAttempt:()=>JSON.stringify({status:'complete',raw_output:f.attempt.raw_output})}).proposal('D1');assert.equal(forged.state,'stale_attempt');assert.equal(forged.provenance_valid,false);
 for(const invalid of['null','[]','true','17','"inert"','bad JSON'])assert.equal(createIntentStore(f.bindings,{readAttempt:()=>invalid}).proposal('D1').state,'invalid_attempt_file');
 const invalid=fixtureAttempt('E4'),store=createIntentStore(invalid.bindings,{readAttempt:()=>JSON.stringify(invalid.attempt)}),p=store.proposal('E4');assert.equal(p.state,'rejected_proposal');assert.equal(p.inspection.parsed_query.source_labeled_date_from,'2018-02-29');assert.equal(p.inspection.policy_state,'invalid_calendar_date');assert.throws(()=>store.review({case_id:'E4',proposal_fingerprint:p.proposal_fingerprint,semantic_confirmation:true}),{code:'REJECTED_INTENT'});
});
test('two-client inspected proposal cannot accept a replacement; only reviewed exact intent can execute and export',async t=>{
 const f=fixtureAttempt();let current=JSON.stringify(f.attempt);const server=await createDesk({readIntentAttempt:()=>current});await new Promise(r=>server.listen(0,'127.0.0.1',r));t.after(()=>new Promise(r=>server.close(r)));const base='http://127.0.0.1:'+server.address().port,call=async(path,body)=>{const r=await fetch(base+path,body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{});return {status:r.status,data:await r.json()};};
 const inspected=(await call('/api/intent-proposal?id=D1')).data;assert.equal((await call('/api/intent-review',{case_id:'D1',proposal_fingerprint:inspected.proposal_fingerprint,semantic_confirmation:false})).status,400);
 current=JSON.stringify(fixtureAttempt('D1',{...f.query,source_weekstatus:'Weekend'}).attempt);assert.equal((await call('/api/intent-review',{case_id:'D1',proposal_fingerprint:inspected.proposal_fingerprint,semantic_confirmation:true})).data.error,'STALE_INTENT');
 const fresh=(await call('/api/intent-proposal?id=D1')).data,review=(await call('/api/intent-review',{case_id:'D1',proposal_fingerprint:fresh.proposal_fingerprint,semantic_confirmation:true})).data;
 const changed=await call('/api/query',{query:{...review.query,source_weekstatus:null},interpretation_confirmed:true,intent_binding:review.binding});assert.equal(changed.data.error,'STALE_INTENT_QUERY');
 const executed=await call('/api/query',{query:review.query,interpretation_confirmed:true,intent_binding:review.binding});assert.equal(executed.data.answer.usage_kwh_exact,'117135.55');assert.equal(executed.data.intent_review_receipt.model_arithmetic_authority,false);
 const exported=await call('/api/receipt',{query:review.query,interpretation_confirmed:true,intent_binding:review.binding,source_csv_sha256:executed.data.source_csv_sha256,query_fingerprint:executed.data.query_fingerprint});assert.equal(exported.status,200);assert.deepEqual(exported.data.receipt,executed.data.receipt);
 current=null;assert.equal((await call('/api/receipt',{query:review.query,interpretation_confirmed:true,intent_binding:review.binding,source_csv_sha256:executed.data.source_csv_sha256,query_fingerprint:executed.data.query_fingerprint})).data.error,'STALE_INTENT');assert.equal((await call('/api/query',{query:f.query,interpretation_confirmed:true})).data.answer.usage_kwh_exact,'959636.71');
});
