import {stageIntent,sourceAuthorityAvailable,reportIntentFailure,preserveSubmittingFocus} from './app.mjs';
const $=id=>document.getElementById(id),fields=['schema_version','operation','source_labeled_date_from','source_labeled_date_to_exclusive','source_weekstatus','source_load_type','unavailable_topic'];let proposal=null,pending=false,generation=0;
function controls(){$('intent-inspect').disabled=pending||!sourceAuthorityAvailable()||!$('intent-case').value;$('intent-use').disabled=pending||!sourceAuthorityAvailable()||proposal?.state!=='requires_human_semantic_review'||!$('intent-semantic-confirm').checked;$('intent-semantic-confirm').disabled=pending||proposal?.state!=='requires_human_semantic_review';}
async function api(path,body){let response,data;try{response=await fetch(path,body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{});data=await response.json();}catch{throw Error('SOURCE_UNAVAILABLE: Server evidence cannot be read. Cached evidence is historical.');}if(!response.ok)throw Error(data.error+': '+data.message);return data;}
function render(){
 $('intent-question').textContent=proposal.question;$('intent-state').textContent=proposal.state==='requires_human_semantic_review'?'Safe structure and policy only; semantic interpretation requires your review.':proposal.state==='not_run'?'NOT RUN · no stored proposal exists. Inspecting does not call the model.':proposal.state.toUpperCase()+' · no acceptance authority.';
 const parsed=proposal.inspection?.parsed_query;$('intent-fields').replaceChildren();for(const field of fields){const row=document.createElement('tr');for(const value of[field,parsed&&Object.hasOwn(parsed,field)?JSON.stringify(parsed[field]):'Not proposed']){const cell=document.createElement('td');cell.textContent=value;row.append(cell);}$('intent-fields').append(row);}
 $('intent-raw').textContent=proposal.raw_output??'No raw model output. Generation requests from UI:0.';$('intent-validation').textContent=JSON.stringify({structure:proposal.inspection?.structural_state??'not_evaluated',policy:proposal.inspection?.policy_state??'not_evaluated',semantic_review:'required; safe shape is not correctness',errors:proposal.inspection?.errors??[],artifact_provenance_valid:proposal.provenance_valid??false,artifact_provenance_errors:proposal.provenance_errors??[],transport:proposal.transport_status??'not_attempted',http_status:proposal.http_status??null,failure:proposal.failure??null,provenance:proposal.provenance},null,2);
 $('intent-binding').textContent=JSON.stringify({case_id:proposal.case_id,question_sha256:proposal.question_sha256,raw_output_sha256:proposal.raw_output_sha256??null,proposal_fingerprint:proposal.proposal_fingerprint,method_bindings:proposal.method_bindings},null,2);controls();
}
function invalidate(reason){++generation;$('intent-semantic-confirm').checked=false;$('intent-state').textContent=reason;controls();}
$('intent-case').onchange=()=>{proposal=null;invalidate('Question selection changed. Inspect its exact stored proposal before review.');$('intent-fields').replaceChildren();$('intent-question').textContent='Selected question has not been inspected.';};
$('intent-semantic-confirm').onchange=controls;
$('intent-inspect').onclick=async()=>{if(pending||!sourceAuthorityAvailable())return;const request=++generation,id=$('intent-case').value,restore=preserveSubmittingFocus();pending=true;$('intent-semantic-confirm').checked=false;controls();$('intent-state').textContent='Loading stored attempt and validating source/protocol binding…';try{const data=await api('/api/intent-proposal?id='+encodeURIComponent(id));if(request!==generation||id!==$('intent-case').value||!sourceAuthorityAvailable())return;proposal=data;render();}catch(e){if(request===generation){reportIntentFailure(e);invalidate('Stored proposal unavailable or historical: '+e.message);}}finally{pending=false;controls();restore();}};
$('intent-use').onclick=async()=>{if(pending||proposal?.state!=='requires_human_semantic_review'||!$('intent-semantic-confirm').checked||!sourceAuthorityAvailable())return;const request=generation,bound=proposal,restore=preserveSubmittingFocus();pending=true;controls();try{const review=await api('/api/intent-review',{case_id:bound.case_id,proposal_fingerprint:bound.proposal_fingerprint,semantic_confirmation:true});if(request!==generation||proposal!==bound||!$('intent-semantic-confirm').checked||!sourceAuthorityAvailable())return;stageIntent(review);$('intent-state').textContent='Human-reviewed interpretation populated the builder; deterministic execution has not started.';}catch(e){reportIntentFailure(e);invalidate('Fresh inspection required: '+e.message);}finally{pending=false;controls();restore();}};
document.addEventListener('p12:manual-change',()=>{if(proposal)invalidate('Builder edited; no model acceptance transfers to changed fields. Reinspect if you want to use the stored proposal.');});
for(const event of['p12:authority-revoked','p12:intent-revoked'])document.addEventListener(event,()=>{proposal=null;invalidate('HISTORICAL INTENT · current source or proposal authority is unavailable. Cached raw evidence is retained.');});
try{const data=await api('/api/intent-cases');for(const item of data.cases){const option=document.createElement('option');option.value=item.id;option.textContent=item.id+' · '+item.phase+' · '+item.question;$('intent-case').append(option);}$('intent-method').textContent=data.protocol_version+' · frozen '+data.freeze_sha256+' · stored/offline only; UI generation requests:0';controls();}catch(e){reportIntentFailure(e);proposal=null;invalidate('Optional intent path unavailable; cached evidence is historical when authority is revoked: '+e.message);}
