"""Actual CPU Chrome UI checks and native capture. Public source + one owned mutation copy."""
import asyncio,hashlib,json,os,shutil,subprocess,tempfile,time,urllib.request
from pathlib import Path
from playwright.async_api import async_playwright,expect
ROOT=Path(__file__).resolve().parents[1];URL='http://127.0.0.1:5122';CHECKS=[]
def check(name,details=None):CHECKS.append({'check':name,'status':'passed','details':details})
def fingerprint(receipt):
    clone=dict(receipt);fp=clone.pop('query_fingerprint');assert hashlib.sha256(json.dumps(clone,separators=(',',':'),ensure_ascii=False).encode()).hexdigest()==fp;return fp
async def record_native_demo(browser,docs):
    context=await browser.new_context(viewport={'width':1440,'height':1000});page=await context.new_page();frames=Path(tempfile.mkdtemp(prefix='p12-native-frames-',dir=ROOT/'private'));stopped=False
    async def capture():
        index=0
        while not stopped:
            started=time.monotonic();await page.screenshot(path=str(frames/f'frame-{index:05d}.jpg'),type='jpeg',quality=80);index+=1;await asyncio.sleep(max(0,.2-(time.monotonic()-started)))
    await ready(page);task=asyncio.create_task(capture())
    try:
        await asyncio.sleep(1);await run(page,start='2018-01-15',end='2018-01-16');await page.locator('#result-panel').evaluate("e=>e.scrollIntoView({block:'start'})");await asyncio.sleep(2);await page.locator('#rows [data-row="95"]').click();await asyncio.sleep(1);await run(page,op='report_missing_or_unresolved_field',topic='co2_mass');await page.locator('#result-panel').evaluate("e=>e.scrollIntoView({block:'start'})");await asyncio.sleep(2);await run(page,op='report_missing_or_unresolved_field',start='2026-09-30',end='2026-10-01',topic='period_coverage');await page.locator('#result-panel').evaluate("e=>e.scrollIntoView({block:'start'})");await asyncio.sleep(2);await run(page,start='2018-01-01',end='2018-02-01');await page.locator('#result-panel').evaluate("e=>e.scrollIntoView({block:'start'})");await asyncio.sleep(2)
    finally:stopped=True;await task;await context.close()
    subprocess.run(['ffmpeg','-y','-hide_banner','-loglevel','error','-framerate','5','-i',str(frames/'frame-%05d.jpg'),'-an','-c:v','libx264','-preset','fast','-crf','27','-pix_fmt','yuv420p','-movflags','+faststart',str(docs/'cpu-demo.mp4')],check=True)
async def ready(page):await page.goto(URL);await expect(page.locator('#identity')).to_contain_text('Verified original CSV')
async def run(page,op='sum_source_usage_kwh',start='',end='',week='ALL',load='ALL',topic=''):
    await page.locator('#operation').select_option(op);await page.locator('#start').fill(start);await page.locator('#end').fill(end);await page.locator('#week').select_option(week);await page.locator('#load').select_option(load)
    if op=='report_missing_or_unresolved_field':await page.locator('#topic').select_option(topic)
    await page.locator('#confirm').check();await page.locator('#run').click();await expect(page.locator('#run')).to_be_enabled();await expect(page.locator('#result-state')).to_contain_text('EXECUTED')
async def main():
    docs=ROOT/'docs';docs.mkdir(exist_ok=True);evidence=ROOT/'evidence';evidence.mkdir(exist_ok=True)
    with tempfile.TemporaryDirectory(prefix='p12-browser-owned-copy-')as owned:
        source=Path(owned)/'source.csv';shutil.copyfile(ROOT/'data/Steel_industry_data.csv',source)
        server=subprocess.Popen(['node','--input-type=module','-e',"import {createDesk} from './server.mjs'; (await createDesk({sourcePath:process.env.P12_SOURCE_TEST})).listen(5122,'127.0.0.1');"],cwd=ROOT,env=dict(os.environ,P12_SOURCE_TEST=str(source)),stdout=subprocess.DEVNULL,stderr=subprocess.DEVNULL)
        try:
            for _ in range(80):
                try:urllib.request.urlopen(URL+'/api/admission',timeout=1).close();break
                except Exception:await asyncio.sleep(.1)
            async with async_playwright()as p:
                browser=await p.chromium.launch(executable_path='/usr/bin/google-chrome',args=['--no-sandbox','--disable-gpu']);ctx=await browser.new_context(viewport={'width':1440,'height':1050},accept_downloads=True,timezone_id='UTC');page=await ctx.new_page();errors=[];page.on('pageerror',lambda e:errors.append(str(e)))
                await ready(page);await page.screenshot(path=str(docs/'admission-desktop.png'));await run(page,start='2018-01-15',end='2018-01-16');await expect(page.locator('#operation-answer')).to_contain_text('3968.64');await expect(page.locator('#row-scope')).to_contain_text('96');await expect(page.locator('#rows')).to_contain_text('15/01/2018 00:00');check('Actual Jan15 exact sum and preserved source ledger midnight position')
                await page.locator('#result-panel').evaluate("e=>e.scrollIntoView({block:'start'})");await page.screenshot(path=str(docs/'energy-desktop.png'))
                first=json.loads(await page.locator('#receipt-binding').inner_text())['query_fingerprint'];await page.locator('#confirm').uncheck();await expect(page.locator('#receipt')).to_be_disabled();await expect(page.locator('#run')).to_be_disabled();await page.locator('#confirm').check()
                async with page.expect_download()as download:await page.locator('#receipt').click()
                downloaded=await download.value;path=await downloaded.path();envelope=json.loads(Path(path).read_text());assert fingerprint(envelope['receipt'])==first;assert envelope['acknowledgment']['download_completion']=='not_established';assert len(envelope['receipt']['contributing_row_ids'])==96;check('Confirmation withdrawal disables export; downloaded immutable receipt matches fingerprint and exact row scope')
                await run(page,start='2018-01-15',end='2018-01-16');second=json.loads(await page.locator('#receipt-binding').inner_text())['query_fingerprint'];assert first==second;check('Repeated canonical query has stable fingerprint, distinct local history entries')
                await page.locator('#rows [data-row="0"]').focus();await page.keyboard.press('Enter');await expect(page.locator('#source-row')).to_be_focused();await expect(page.locator('#source-row')).to_contain_text('field_spans');check('Native Enter opens exact source evidence at named focusable destination')
                await page.locator('#confirm').focus();await page.keyboard.press('Tab');await expect(page.locator('#run')).to_be_focused();await page.keyboard.press('Enter');await expect(page.locator('#run')).to_be_enabled();await expect(page.locator('#run')).to_be_focused();check('Tab/Enter execution retains explicit control focus')
                await run(page,op='count_source_rows');await expect(page.locator('#energy-chart-panel')).to_be_hidden();assert 'kWh'not in await page.locator('#history .history-item').last.inner_text();assert 'filter_hash'not in await page.locator('#receipt-binding').inner_text();await expect(page.locator('#operation-answer')).to_contain_text('35040');check('Non-energy selected rows do not display empty energy chart or invent kWh history; policy digest named correctly')
                await run(page,op='report_missing_or_unresolved_field',topic='co2_mass');await expect(page.locator('#operation-answer')).to_contain_text('unit_and_derivation_unresolved');await expect(page.locator('#operation-answer')).to_contain_text('"value": null');await page.locator('#result-panel').evaluate("e=>e.scrollIntoView({block:'start'})");await page.screenshot(path=str(docs/'unresolved-desktop.png'));check('Carbon unit/derivation remains explicitly unresolved with no numeric answer')
                for start,end,status in [('2018-02-29','2018-03-01','invalid_calendar_date'),('2018-02-02','2018-02-01','invalid_date_range'),('2026-09-30','2026-10-01','period_not_in_historical_source'),('2017-12-31','2018-01-02','scope_not_fully_covered')]:
                    await run(page,op='report_missing_or_unresolved_field',start=start,end=end,topic='period_coverage');await expect(page.locator('#operation-answer')).to_contain_text(status);await expect(page.locator('#operation-answer')).to_contain_text('"count": null')
                check('Actual browser calendar/range/wholly outside/partial coverage stay distinct nonnumeric states');await page.locator('#result-panel').evaluate("e=>e.scrollIntoView({block:'start'})");await page.screenshot(path=str(docs/'partial-coverage-desktop.png'))
                await run(page,start='2018-01-01',end='2018-01-02',week='Weekday',load='Maximum_Load');await expect(page.locator('#operation-answer')).to_contain_text('empty_selection');await expect(page.locator('#empty-message')).to_contain_text('EMPTY');await expect(page.locator('#operation-answer')).to_contain_text('"usage_kwh_exact": null');check('Covered empty AND selection is empty, not measured zero or missing')
                await run(page,start='2018-11-07',end='2018-11-08');zero=page.locator('#rows tr',has=page.locator('[data-row]')).last;await expect(zero).to_contain_text('csv-line-29857');await expect(zero).to_contain_text('07/11/2018 00:00');await zero.locator('button').click();await expect(page.locator('#source-row')).to_contain_text('"Usage_kWh": "0"');await expect(page.locator('#source-row')).to_contain_text('"usage_status": "valid"')
                await page.screenshot(path=str(docs/'stored-source-zero-desktop.png'));check('Stored source zero retains original raw label, row ID and valid numeric evidence; no physical-zero claim')
                # Hold a completed HTTP response while the user changes inputs and chooses later focus.
                gate=asyncio.Event();issued=asyncio.Event()
                async def delayed(route):response=await route.fetch();issued.set();await gate.wait();await route.fulfill(response=response)
                await page.route('**/api/query',delayed);await page.locator('#confirm').check();await page.locator('#run').click();await issued.wait();await page.locator('#start').fill('2018-01-15');await page.locator('#end').fill('2018-01-16');await page.locator('#end').focus();gate.set();await expect(page.locator('#result-state')).to_have_text('PREVIOUS EXECUTED QUERY');await expect(page.locator('#receipt')).to_be_disabled();await expect(page.locator('#end')).to_be_focused();await expect(page.locator('#executed-filter')).to_contain_text('2018-11-07');await page.unroute('**/api/query',delayed);check('Delayed executed response remains historical after input change and preserves later explicit focus')
                await page.locator('#result-panel').evaluate("e=>e.scrollIntoView({block:'start'})");await page.screenshot(path=str(docs/'stale-query-desktop.png'))
                # A late original-row response cannot replace the current selected date ledger.
                await run(page,start='2018-01-01',end='2018-02-01');await expect(page.locator('#row-scope')).to_contain_text('2018-01-01');rowgate=asyncio.Event();rowissued=asyncio.Event()
                async def delayedrows(route):response=await route.fetch();rowissued.set();await rowgate.wait();await route.fulfill(response=response)
                await page.route('**/api/rows?*date_label=2018-01-02&*',delayedrows);await page.locator('#day').select_option('2018-01-02');await rowissued.wait();await page.locator('#day').select_option('2018-01-03');await expect(page.locator('#row-scope')).to_contain_text('2018-01-03');rowgate.set();await asyncio.sleep(.15);await expect(page.locator('#row-scope')).to_contain_text('2018-01-03');await page.unroute('**/api/rows?*date_label=2018-01-02&*',delayedrows);check('Late ledger response cannot overwrite a newer explicit date selection');await page.locator('#result-panel').evaluate("e=>e.scrollIntoView({block:'start'})");await page.screenshot(path=str(docs/'energy-desktop.png'))
                titles=[]
                for zone in ['UTC','America/New_York']:
                    zonecontext=await browser.new_context(timezone_id=zone);zp=await zonecontext.new_page();await ready(zp);await run(zp,start='2018-01-15',end='2018-01-16');titles.append(await zp.locator('#chart rect title').first.text_content());await zonecontext.close()
                assert titles[0]==titles[1]and '15/01/2018'in titles[0]and 'UTC'not in titles[0];check('Chart raw source-label tooltip is identical across browser timezones',titles[0])
                mobile=await browser.new_context(viewport={'width':390,'height':844},device_scale_factor=1);mp=await mobile.new_page();await ready(mp);await run(mp,start='2018-01-01',end='2018-02-01');dimensions=await mp.evaluate("({page:document.documentElement.scrollWidth,viewport:innerWidth,chart:document.querySelector('#chart').getBoundingClientRect().width,minText:Math.min(...Array.from(document.querySelectorAll('.metric span,pre,table,header span,label,footer')).filter(e=>e.offsetParent).map(e=>parseFloat(getComputedStyle(e).fontSize)))})");assert dimensions['page']<=390 and dimensions['chart']>=1200 and dimensions['minText']>=14;await mp.screenshot(path=str(docs/'energy-mobile-390.png'),full_page=True);check('390px layout has no page overflow, native Gantt-free chart scroll, meaningful text>=14px',dimensions);await mobile.close()
                assert not errors,errors;check('Actual Chrome runtime has no unhandled page exceptions')
                # Demo context records only native CPU actions, with no simulated model output.
                await record_native_demo(browser,docs)
                # Mutate only owned source copy; actual source remains byte-identical.
                await run(page,start='2018-01-15',end='2018-01-16');source.write_bytes(source.read_bytes()+b'changed');await page.locator('#receipt').click();await expect(page.locator('#result-state')).to_contain_text('RE-ADMISSION REQUIRED');await expect(page.locator('#receipt')).to_be_disabled();await expect(page.locator('#confirm')).not_to_be_checked();assert hashlib.sha256((ROOT/'data/Steel_industry_data.csv').read_bytes()).hexdigest()=='9b1cee6f9cb9cd9df2b95814ca90a9a2ff15b7f5f1fba0fae3c643e82072eacc';check('Source-byte change denies old receipt and clears confirmation, original file unchanged');await ctx.close();await browser.close()
            out={'kind':'Executed CPU-only native Chrome engineering regressions','model_calls':0,'checks_passed':len(CHECKS),'checks':CHECKS,'source_csv_sha256':'9b1cee6f9cb9cd9df2b95814ca90a9a2ff15b7f5f1fba0fae3c643e82072eacc','capture_note':'Actual app and public UCI source. Chart geometry approximate, authoritative decimals from CPU. No inference or live system.'};(evidence/'browser-checks.json').write_text(json.dumps(out,indent=2)+'\n');print(json.dumps({'checks_passed':len(CHECKS),'model_calls':0}))
        finally:server.terminate();server.wait(timeout=5)
if __name__=='__main__':asyncio.run(main())
